### ISSUE TITLE
Does it really works?

### ISSUE THREAD

**Issue by jgmdev** [google/recki-ct#13]
I was testing this project but instead of a performance gain I see a performance degradation... Am I doing something wrong?

```
php -v
PHP 5.6.2 (cli) (built: Oct 17 2014 09:51:11) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
```
# 

```
php -r "phpinfo();" | grep JIT
JITFU
JIT-Fu support => enabled
```
# 

```
php examples/01-basic-usage.php 
PHP completed in 0.0168 seconds
ReckiCT completed in 0.0326 seconds
```

**Comment by ircmaxell** [comment]
Try running the other 2 examples.

The first possibly will run slower, because it's a really trivial function, so the overhead of dispatch (calling) will be the dominant factor. See the comment in the code:

```
 * For very simple functions like the one we are testing here, we don't expect
 * a lot of gain (if any), since the overhead of the functional call will dominate
 * the runtime.
```

Instead, examples 2 and 3 do a lot more work, so should see a significantly higher gain.

**Comment by jgmdev** [comment]
The example 2 throws some error, seems like I'm missing some dependency:

```
php examples/02-fibo.php 
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unknown type encountered: unknown' in recki-ct/lib/ReckiCT/Compiler/JitFu/Compiler.php:275
Stack trace:
#0 recki-ct/lib/ReckiCT/Compiler/JitFu/Compiler.php(140): ReckiCT\Compiler\JitFu\Compiler->createType('unknown')
#1 recki-ct/lib/ReckiCT/Compiler/JitFu/Compiler.php(104): ReckiCT\Compiler\JitFu\Compiler->compileInstruction(Array, Object(stdClass))
#2 [internal function]: JITFU\Func->ReckiCT\Compiler\JitFu\{closure}(Array)
#3 recki-ct/lib/ReckiCT/Compiler/JitFu/Compiler.php(108): JITFU\Func->implement(Object(Closure))
#4 recki-ct/lib/ReckiCT/Compiler/Compiler.php(32): ReckiCT\Compiler\JitFu\Compiler->convertToCallable(Array)
#5recki-ct/lib/ReckiCT/Jit.php(309): ReckiCT\Compiler\Compiler->compile('function fibo l...')
#6 recki-ct/lib/ReckiCT/Jit.php(126): ReckiCT\Jit->compileFunctionJitFu('fibo')
#7 recki-ct in recki-ct/lib/ReckiCT/Compiler/JitFu/Compiler.php on line 275
```

The fibonnaci sample does works, and it is a lot faster, so for numeric processing ReckiCT would shine

```
php examples/03-fibo-using-ir.php 
PHP completed fibo(30)==1346269 in 0.3366 seconds
ReckiCT completed fibo(30)==1346269 in 0.0098 seconds
```
